export const MY_ORDERS_FETCHING = 'MY_ORDERS_FETCHING';
export const MY_ORDERS_FETCHED = 'MY_ORDERS_FETCHED';
export const MY_ORDERS_FETCHED_ERR = 'MY_ORDERS_FETCHED_ERR';

// Получить один заказ по id
export const ONE_ORDER_FETCHING = 'ONE_ORDER_FETCHING';
export const ONE_ORDER_FETCHED = 'ONE_ORDER_FETCHED';
export const ONE_ORDER_FETCHED_ERR = 'ONE_ORDER_FETCHED_ERR';
