// Для списка мастеров
export const MASTER_LIST_FETCHING = 'MASTER_LIST_FETCHING';
export const MASTER_LIST_FETCHED = 'MASTER_LIST_FETCHED';
export const MASTER_LIST_FETCHED_ERR = 'MASTER_LIST_FETCHED_ERR';
