export const LOCATION_TYPES_FETCHING = 'LOCATION_TYPES_FETCHING';
export const LOCATION_TYPES_FETCHED = 'LOCATION_TYPES_FETCHED';
export const LOCATION_TYPES_FETCHED_ERR = 'LOCATION_TYPES_FETCHED_ERR';
